[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[start]
cmd = "npm run start"