[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd storyboard-collab && npm install --force"]

[phases.build]
cmds = ["cd storyboard-collab && npm run build"]

[start]
cmd = "cd storyboard-collab && npm run start"