[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/storage-info"
  healthcheckTimeout = 30
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
