[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run init-db"
  nixpacksPlan = """
    [phases.setup]
    nixPkgs = ['nodejs-18_x', 'npm-9_x']
  """

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3